-- Seed all exercises into public.exercises
CREATE TABLE IF NOT EXISTS public.exercises (
  id text PRIMARY KEY,
  name text NOT NULL,
  category text NOT NULL,
  equipment text NOT NULL,
  is_compound boolean NOT NULL DEFAULT false,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.exercises ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read exercises" ON public.exercises;
CREATE POLICY "Public read exercises" ON public.exercises FOR SELECT USING (true);

INSERT INTO public.exercises (id, name, category, equipment, is_compound)
VALUES
  ('ex-0', 'Bankdrücken', 'Brust', 'Langhantel', false),
  ('ex-1', 'Schrägbankdrücken', 'Brust', 'Langhantel', false),
  ('ex-2', 'Negativbankdrücken', 'Brust', 'Langhantel', false),
  ('ex-3', 'Kurzhantel-Bankdrücken', 'Brust', 'Kurzhantel', false),
  ('ex-4', 'Kurzhantel-Schrägbankdrücken', 'Brust', 'Kurzhantel', false),
  ('ex-5', 'Fliegende Kurzhantel (Schrägbank)', 'Brust', 'Kurzhantel', false),
  ('ex-6', 'Butterfly', 'Brust', 'Maschine', false),
  ('ex-7', 'Cable Crossover', 'Brust', 'Kabelzug', false),
  ('ex-8', 'Dips (Brustfokus)', 'Brust', 'Körpergewicht', false),
  ('ex-9', 'Liegestütze', 'Brust', 'Körpergewicht', false),
  ('ex-10', 'Pec-Deck', 'Brust', 'Maschine', false),
  ('ex-11', 'Negativbankdrücken (Kurzhantel)', 'Brust', 'Kurzhantel', false),
  ('ex-12', 'Kabel-Butterfly liegend (Bank)', 'Brust', 'Kabelzug', false),
  ('ex-13', 'Kabel-Butterfly stehend', 'Brust', 'Kabelzug', false),
  ('ex-14', 'Kabel-Low-Fly stehend', 'Brust', 'Kabelzug', false),
  ('ex-15', 'Brustpresse (Maschine)', 'Brust', 'Maschine', false),
  ('ex-16', 'Schrägbankdrücken (Maschine)', 'Brust', 'Maschine', false),
  ('ex-17', 'Kurzhantel-Bankdrücken (Neutralgriff)', 'Brust', 'Kurzhantel', false),
  ('ex-18', 'Kurzhantel-Bankdrücken (Untergriff)', 'Brust', 'Kurzhantel', false),
  ('ex-19', 'Schrägbankdrücken (Multipresse)', 'Brust', 'Multipresse', false),
  ('ex-20', 'Bankdrücken (Multipresse)', 'Brust', 'Multipresse', false),
  ('ex-21', 'Klimmzüge', 'Rücken', 'Körpergewicht', false),
  ('ex-22', 'Latzug breit', 'Rücken', 'Kabelzug', false),
  ('ex-23', 'Latzug eng (Untergriff)', 'Rücken', 'Kabelzug', false),
  ('ex-24', 'Langhantelrudern vorgebeugt', 'Rücken', 'Langhantel', false),
  ('ex-25', 'Kurzhantelrudern einarmig', 'Rücken', 'Kurzhantel', false),
  ('ex-26', 'T-Bar Rudern', 'Rücken', 'Langhantel', false),
  ('ex-27', 'Kabelrudern sitzend', 'Rücken', 'Kabelzug', false),
  ('ex-28', 'Kreuzheben', 'Rücken', 'Langhantel', false),
  ('ex-29', 'Rumänisches Kreuzheben', 'Rücken', 'Langhantel', false),
  ('ex-30', 'Good Mornings', 'Rücken', 'Langhantel', false),
  ('ex-31', 'Hyperextensions', 'Rücken', 'Körpergewicht', false),
  ('ex-32', 'Pull-Over', 'Rücken', 'Kurzhantel', false),
  ('ex-33', 'Nackenheben (Shrugs, Langhantel)', 'Rücken', 'Langhantel', false),
  ('ex-34', 'Shrugs (Kurzhantel)', 'Rücken', 'Kurzhantel', false),
  ('ex-35', 'Langhantelrudern vorgebeugt (Untergriff)', 'Rücken', 'Langhantel', false),
  ('ex-36', 'Einarmiges Rudern (Maschine, sitzend)', 'Rücken', 'Maschine', false),
  ('ex-37', 'Kreuzheben (Maschine)', 'Rücken', 'Maschine', false),
  ('ex-38', 'Kreuzheben (Multipresse)', 'Rücken', 'Multipresse', false),
  ('ex-39', 'Trapezmaschine', 'Rücken', 'Maschine', false),
  ('ex-40', 'Überzüge (Maschine)', 'Rücken', 'Maschine', false),
  ('ex-41', 'Einarmiges Ziehen (Maschine)', 'Rücken', 'Maschine', false),
  ('ex-42', 'Angel & Devil', 'Rücken', 'Körpergewicht', false),
  ('ex-43', 'T-Bar Rudern (Maschine)', 'Rücken', 'Maschine', false),
  ('ex-44', 'Kreuzheben (Hexbar)', 'Rücken', 'Langhantel', false),
  ('ex-45', 'Vorgebeugtes Rudern (Langhantel, Obergriff)', 'Rücken', 'Langhantel', false),
  ('ex-46', 'Nackenheben / Shrugs (Multipresse)', 'Nacken', 'Multipresse', false),
  ('ex-47', 'Nackenheben / Shrugs (Maschine)', 'Nacken', 'Maschine', false),
  ('ex-48', 'Nackenheben / Shrugs (Kabelzug)', 'Nacken', 'Kabelzug', false),
  ('ex-49', 'Nackenheben / Shrugs (Kurzhantel)', 'Nacken', 'Kurzhantel', false),
  ('ex-50', 'Frontheben mit Gewichtsscheibe', 'Nacken', 'Gewichtsscheibe', false),
  ('ex-51', 'Schulterdrücken (Langhantel)', 'Schultern', 'Langhantel', false),
  ('ex-52', 'Schulterdrücken (Kurzhantel, sitzend)', 'Schultern', 'Kurzhantel', false),
  ('ex-53', 'Seitheben (Kurzhantel)', 'Schultern', 'Kurzhantel', false),
  ('ex-54', 'Frontheben', 'Schultern', 'Kurzhantel', false),
  ('ex-55', 'Reverse Butterfly', 'Schultern', 'Maschine', false),
  ('ex-56', 'Face Pulls', 'Schultern', 'Kabelzug', false),
  ('ex-57', 'Arnold Press', 'Schultern', 'Kurzhantel', false),
  ('ex-58', 'Aufrechtes Rudern', 'Schultern', 'Langhantel', false),
  ('ex-59', 'Schulterdrücken (Maschine)', 'Schultern', 'Maschine', false),
  ('ex-60', 'Kabel-Seitheben', 'Schultern', 'Kabelzug', false),
  ('ex-61', 'Seitheben angelehnt an Bank (Kurzhantel)', 'Schultern', 'Kurzhantel', false),
  ('ex-62', 'Schulterdrücken (Multipresse)', 'Schultern', 'Multipresse', false),
  ('ex-63', 'Kabelzug hintere Schulter', 'Schultern', 'Kabelzug', false),
  ('ex-64', 'Seitheben (Maschine)', 'Schultern', 'Maschine', false),
  ('ex-65', 'Langhantel-Bizepscurls', 'Bizeps', 'Langhantel', false),
  ('ex-66', 'SZ-Stangen-Curls', 'Bizeps', 'Langhantel', false),
  ('ex-67', 'Kurzhantel-Curls', 'Bizeps', 'Kurzhantel', false),
  ('ex-68', 'Hammer-Curls', 'Bizeps', 'Kurzhantel', false),
  ('ex-69', 'Konzentrationscurls', 'Bizeps', 'Kurzhantel', false),
  ('ex-70', 'Scott-Curls (Predigerbank)', 'Bizeps', 'Langhantel', false),
  ('ex-71', 'Kabel-Bizepscurls', 'Bizeps', 'Kabelzug', false),
  ('ex-72', '21er Curls', 'Bizeps', 'Langhantel', false),
  ('ex-73', 'Über-Kreuz-Hammercurls', 'Bizeps', 'Kurzhantel', false),
  ('ex-74', 'Bizepscurls (Multipresse)', 'Bizeps', 'Multipresse', false),
  ('ex-75', 'Einarmige Bizepscurls (Kabel)', 'Bizeps', 'Kabelzug', false),
  ('ex-76', 'Bizeps-Maschine', 'Bizeps', 'Maschine', false),
  ('ex-77', 'Trizepsdrücken am Kabel (Seil)', 'Trizeps', 'Kabelzug', false),
  ('ex-78', 'Trizepsdrücken am Kabel (Stange)', 'Trizeps', 'Kabelzug', false),
  ('ex-79', 'Enges Bankdrücken', 'Trizeps', 'Langhantel', false),
  ('ex-80', 'Dips (Trizepsfokus)', 'Trizeps', 'Körpergewicht', false),
  ('ex-81', 'French Press', 'Trizeps', 'Langhantel', false),
  ('ex-82', 'Kickbacks', 'Trizeps', 'Kurzhantel', false),
  ('ex-83', 'Overhead-Trizepsdrücken', 'Trizeps', 'Kurzhantel', false),
  ('ex-84', 'Trizeps-Maschine', 'Trizeps', 'Maschine', false),
  ('ex-85', 'Enges Bankdrücken (Multipresse, V-Griff)', 'Trizeps', 'Multipresse', false),
  ('ex-86', 'Kniebeugen', 'Beine', 'Langhantel', false),
  ('ex-87', 'Frontkniebeugen', 'Beine', 'Langhantel', false),
  ('ex-88', 'Beinpresse', 'Beine', 'Maschine', false),
  ('ex-89', 'Ausfallschritte', 'Beine', 'Kurzhantel', false),
  ('ex-90', 'Bulgarian Split Squats', 'Beine', 'Kurzhantel', false),
  ('ex-91', 'Beinstrecker', 'Beine', 'Maschine', false),
  ('ex-92', 'Beinbeuger liegend', 'Beine', 'Maschine', false),
  ('ex-93', 'Beinbeuger sitzend', 'Beine', 'Maschine', false),
  ('ex-94', 'Hack Squat', 'Beine', 'Maschine', false),
  ('ex-95', 'Goblet Squats', 'Beine', 'Kurzhantel', false),
  ('ex-96', 'Step-Ups', 'Beine', 'Kurzhantel', false),
  ('ex-97', 'Sumo-Kniebeugen', 'Beine', 'Langhantel', false),
  ('ex-98', 'Innenschenkel-Maschine (Adduktion)', 'Beine', 'Maschine', false),
  ('ex-99', 'Außenschenkel-Maschine (Abduktion)', 'Beine', 'Maschine', false),
  ('ex-100', 'Kniebeugen (Multipresse)', 'Beine', 'Multipresse', false),
  ('ex-101', 'Frontkniebeugen (Multipresse)', 'Beine', 'Multipresse', false),
  ('ex-102', 'Ausfallschritte vorwärts (Multipresse)', 'Beine', 'Multipresse', false),
  ('ex-103', 'Ausfallschritte rückwärts (Multipresse)', 'Beine', 'Multipresse', false),
  ('ex-104', 'Beinpresse frontal (Maschine)', 'Beine', 'Maschine', false),
  ('ex-105', 'Hip Thrust', 'Gesäß', 'Langhantel', false),
  ('ex-106', 'Hip Thrust (Maschine)', 'Gesäß', 'Maschine', false),
  ('ex-107', 'Kabelzug Kickback', 'Gesäß', 'Kabelzug', false),
  ('ex-108', 'Hüftabduktion (Maschine)', 'Gesäß', 'Maschine', false),
  ('ex-109', 'Beckenheben (Glute Bridge)', 'Gesäß', 'Körpergewicht', false),
  ('ex-110', 'Cable Pull-Through', 'Gesäß', 'Kabelzug', false),
  ('ex-111', 'Wadenheben stehend', 'Waden', 'Maschine', false),
  ('ex-112', 'Wadenheben sitzend', 'Waden', 'Maschine', false),
  ('ex-113', 'Wadenheben stehend (Multipresse)', 'Waden', 'Multipresse', false),
  ('ex-114', 'Wadenheben an der Beinpresse', 'Waden', 'Maschine', false),
  ('ex-115', 'Eselwadenheben', 'Waden', 'Maschine', false),
  ('ex-116', 'Crunches', 'Bauch', 'Körpergewicht', false),
  ('ex-117', 'Plank (Unterarmstütz)', 'Bauch', 'Körpergewicht', false),
  ('ex-118', 'Beinheben hängend', 'Bauch', 'Körpergewicht', false),
  ('ex-119', 'Russian Twists', 'Bauch', 'Körpergewicht', false),
  ('ex-120', 'Cable Crunches', 'Bauch', 'Kabelzug', false),
  ('ex-121', 'Sit-Ups', 'Bauch', 'Körpergewicht', false),
  ('ex-122', 'Ab Wheel Rollout', 'Bauch', 'Körpergewicht', false),
  ('ex-123', 'Mountain Climbers', 'Bauch', 'Körpergewicht', false),
  ('ex-124', 'Seitliche Crunches', 'Bauch', 'Körpergewicht', false),
  ('ex-125', 'Fahrradfahren (Bicycle Crunches)', 'Bauch', 'Körpergewicht', false),
  ('ex-126', 'Kerze mit Beinheben', 'Bauch', 'Körpergewicht', false),
  ('ex-127', 'Beine hochhalten (Static Hold)', 'Bauch', 'Körpergewicht', false),
  ('ex-128', 'Knietucks / Beine ziehen (liegend)', 'Bauch', 'Körpergewicht', false),
  ('ex-129', 'Beine heben und senken (sitzend)', 'Bauch', 'Körpergewicht', false),
  ('ex-130', 'Kettlebell Swings', 'Ganzkörper', 'Kettlebell', false),
  ('ex-131', 'Burpees', 'Ganzkörper', 'Körpergewicht', false),
  ('ex-132', 'Clean and Press', 'Ganzkörper', 'Langhantel', false),
  ('ex-133', 'Farmer''s Walk', 'Ganzkörper', 'Kurzhantel', false),
  ('ex-134', 'Turkish Get-Up', 'Ganzkörper', 'Kettlebell', false),
  ('ex-135', 'Thruster', 'Ganzkörper', 'Langhantel', false),
  ('ex-136', 'Box Jump (Box-Springen)', 'Ganzkörper', 'Körpergewicht', false)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  category = excluded.category,
  equipment = excluded.equipment,
  is_compound = excluded.is_compound;
