import Foundation

/*
  Die Übersetzungstabellen — ohne jede Abhängigkeit zum Datenmodell.

  Sie lagen in I18n.swift, zusammen mit Helfern, die Exercise, MuscleCategory
  und SplitType kennen. Damit ließ sich die Datei nur dort übersetzen, wo auch
  das ganze Modell liegt — die Widget-Erweiterung fiel raus, und die
  Sperrbildschirm-Karte blieb deshalb fest deutsch.

  Hier stehen nur Zeichenketten. Diese Datei wird in App UND Erweiterung
  übersetzt; welche Sprache gilt, gibt der Aufrufer mit.
*/
public enum Strings {

    /// `Strings.t("live.setOf", lang: "en", ["current": "2", "total": "4"])`.
    /// Unbekannte Schlüssel geben sich selbst zurück, genau wie im Web.
    public static func t(_ key: String, lang: String, _ vars: [String: String] = [:]) -> String {
        let table = lang == "en" ? en : de
        let raw = table[key] ?? key
        guard !vars.isEmpty else { return raw }
        var out = raw
        for (k, v) in vars {
            out = out.replacingOccurrences(of: "{\(k)}", with: v)
        }
        return out
    }

    static let de: [String: String] = [
        "music.emptyTextNative": "Wähle Titel aus deiner Mediathek. Aus Apple Music geladene Titel laufen auch ohne Empfang.",
        "music.denied": "Ohne Zugriff auf die Mediathek kann die App keine Musik abspielen. Du kannst ihn in den Einstellungen erlauben.",
        "app.subtitle": "Smartplan & KI-Coach",
        "greeting.title": "Hallo, {name}!",
        "greeting.guestName": "Athlet",
        "greeting.coachBadge": "KI-COACH",
        "greeting.sentence": "Bereit für dein nächstes Workout?",
        "greeting.sentence.1": "Bereit für heute, {name}?",
        "greeting.sentence.2": "{name}, Zeit für Gains.",
        "greeting.sentence.3": "Auf geht's, {name}!",
        "greeting.sentence.4": "Dein Workout wartet, {name}.",
        "greeting.sentence.5": "Gib heute richtig Gas, {name}.",
        "greeting.sentence.6": "{name}, lass uns starten.",
        "greeting.sentence.7": "Fokus an, Welt aus, {name}.",
        "greeting.sentence.8": "Jeder Satz zählt, {name}.",
        "greeting.sentence.9": "Zeit für Höchstleistungen, {name}.",
        "greeting.sentence.10": "Stärker als gestern, {name}.",
        "greeting.sentence.11": "{name}, besiege deinen inneren Schweinehund!",
        "greeting.sentence.12": "Disziplin schlägt Motivation, {name}.",
        "greeting.sentence.13": "Heute wird Geschichte geschrieben, {name}.",
        "greeting.sentence.14": "Deine Muskeln warten auf dich, {name}.",
        "greeting.sentence.15": "Keine Ausreden, nur Ergebnisse, {name}.",
        "greeting.sentence.16": "{name}, bring das Eisen zum Glühen.",
        "greeting.sentence.17": "Fortschritt entsteht außerhalb der Komfortzone, {name}.",
        "greeting.sentence.18": "Ziele vor Augen, Fokus im Kopf, {name}.",
        "greeting.sentence.19": "{name}, heute holst du das Maximum raus!",
        "greeting.sentence.20": "Ein starker Geist in einem starken Körper, {name}.",
        "greeting.sentence.21": "Erfolg ist die Summe kleiner Anstrengungen, {name}.",
        "greeting.sentence.22": "{name}, mach dieses Training zu deinem Meisterwerk.",
        "greeting.sentence.23": "Volle Konzentration auf jede Wiederholung, {name}.",
        "greeting.sentence.24": "Bleib dran, {name} – es lohnt sich!",
        "greeting.sentence.25": "Willkommen zurück in der Schmerzzone des Wachstums, {name}.",
        "auth.nameLabel": "DEIN VORNAME / NAME",
        "auth.namePlaceholder": "z. B. Max",
        "auth.emailLabel": "E-MAIL",
        "auth.passwordLabel": "PASSWORT",
        "auth.passwordConfirmLabel": "PASSWORT WIEDERHOLEN",
        "auth.passwordsDoNotMatch": "Die Passwörter stimmen nicht überein.",
        "auth.createAccountHeader": "KONTO ERSTELLEN",
        "auth.signInHeader": "ANMELDEN",
        "auth.toSignInPrompt": "Schon ein Konto? Anmelden",
        "auth.toSignUpPrompt": "Noch kein Konto? Registrieren",
        "auth.forgotPassword": "Passwort vergessen?",
        "auth.forgotPasswordHeader": "PASSWORT ZURÜCKSETZEN",
        "auth.forgotPasswordHint": "Gib deine E-Mail-Adresse ein. Wir senden dir einen Link, um dein Passwort zurückzusetzen.",
        "auth.resetPasswordSubmit": "LINK ANFORDERN",
        "auth.resetPasswordSent": "Falls ein Konto mit dieser E-Mail existiert, wurde eine E-Mail zum Zurücksetzen versendet. Bitte prüfe dein Postfach.",
        "auth.backToSignIn": "Zurück zur Anmeldung",
        "proScreen.restorePurchases": "Käufe wiederherstellen",
        "proScreen.featureTitle": "Alle Pro-Vorteile im Überblick",
        "proScreen.badge": "PREMIUM",
        "proScreen.billedYearly": "jährlich abgerechnet",
        "proScreen.billedMonthly": "monatlich abgerechnet",
        "proScreen.subscribeNow": "Jetzt PRO aktivieren",
        "proScreen.secureCheckout": "Sichere Zahlung über Apple In-App-Kauf",
        "method.standard": "3x3x3",
        "method.standardLong": "3x3x3 Methode",
        "tabs.generator": "GENERATOR",
        "tabs.trainingsplan": "TRAININGSPLAN",
        "tabs.plans": "PLÄNE",
        "tabs.progress": "FORTSCHRITT",
        "tabs.saved": "GESPEICHERT",
        "tabs.favorites": "FAVORITEN",
        "tabs.ai": "KI-COACH",
        "nav.getPro": "PRO HOLEN",
        "nav.signOut": "Abmelden",
        "mode.dice": "Würfeln",
        "mode.ai": "KI-Coach",
        "mode.aiBadge": "PRO",
        "gen.split": "Split wählen",
        "gen.muscles": "Muskelgruppen",
        "gen.count": "Anzahl Übungen",
        "gen.method": "Trainingsmethode",
        "gen.rest": "Pause pro Satz",
        "gen.roll": "WÜRFELN",
        "gen.remix": "Ganzen Plan neu mischen",
        "gen.rerollOne": "Neu würfeln",
        "gen.sets": "Sätze",
        "gen.reps": "Wdh.",
        "gen.restShort": "Pause",
        "gen.namePlaceholder": "Name, z. B. Aktueller Plan",
        "gen.save": "Speichern",
        "gen.empty": "Noch kein Plan gewürfelt.",
        "gen.emptyHint": "Split wählen und auf „WÜRFELN“ tippen.",
        "gen.savedAs": "„{name}“ gespeichert!",
        "gen.defaultName": "Plan vom {date}",
        "ai.title": "Dein Plan, von der KI gebaut",
        "ai.intro": "Ein paar Fragen — daraus baut der KI-Coach einen Trainingsplan, der zu dir passt.",
        "ai.goal": "Ziel",
        "ai.goal.muscle": "Muskelaufbau",
        "ai.goal.strength": "Maximalkraft",
        "ai.goal.definition": "Definition",
        "ai.goal.fitness": "Allgemeine Fitness",
        "ai.goal.abnehmen": "Abnehmen & Fettverbrennung",
        "ai.experience": "Erfahrung",
        "ai.experience.beginner": "Anfänger",
        "ai.experience.intermediate": "Fortgeschritten",
        "ai.experience.advanced": "Sehr erfahren",
        "ai.exp.beginner": "Anfänger",
        "ai.exp.intermediate": "Fortgeschritten",
        "ai.exp.advanced": "Sehr erfahren",
        "ai.days": "Trainingstage",
        "ai.duration": "Dauer pro Einheit",
        "ai.minutes": "{n} Min",
        "ai.equipment": "Verfügbares Equipment",
        "ai.equipmentAll": "Alles",
        "ai.focus": "Schwerpunkt (optional)",
        "ai.limitations": "Einschränkungen (optional)",
        "ai.limitationsPlaceholder": "z. B. Knieprobleme, kein Überkopfdrücken, Bandscheibenvorfall …",
        "ai.weeks": "Planlänge",
        "ai.weeksValue": "{n} Wochen",
        "ai.submit": "KI-PLAN ERSTELLEN",
        "ai.videoUnlockTitle": "Kostenlos freischalten",
        "ai.videoUnlockDesc": "Schau 3 kurze Videos an, um deinen KI-Plan kostenlos zu berechnen. Oder hole dir Pro für werbefreie, unbegrenzte Pläne.",
        "ai.videoUnlockButton": "Video ansehen ({current}/{total})",
        "ai.videoUnlocked": "Freigeschaltet!",
        "ai.savingIsProFeature": "Pläne dauerhaft in deiner Mediathek speichern ist ein Pro-Feature.",
        "ai.savingMealIsProFeature": "Meal Guides dauerhaft speichern ist ein Pro-Feature.",
        "ads.sponsored": "Anzeige",
        "ads.removeAds": "WERBEFREI",
        // Der KI-Coach baut keinen Ersatzplan mehr — er sagt, was los ist.
        // Freundlich im Ton, konkret in der Sache: der Nutzer soll wissen, ob
        // Warten, Anmelden oder Nochmal-Drücken hilft.
        "ai.errorTitle": "Der Coach macht gerade Pause",
        "ai.errorOffline": "Er ist nicht erreichbar — meistens liegt's am Netz. Deine Eingaben bleiben stehen, probier es gleich nochmal.",
        "ai.errorGarbled": "Er hat sich verhaspelt und nichts Brauchbares geliefert. Einmal nochmal drücken hilft fast immer.",
        "ai.errorLimit": "Für heute hat er genug Pläne gebaut. Morgen ist er wieder da.",
        "ai.errorSignedOut": "Deine Sitzung ist abgelaufen. Melde dich neu an, dann geht's weiter.",
        "ai.privacyConsentNotice": "Mit dem Erstellen willigst du ein, dass deine Körper- und Fitnessdaten (Größe, Gewicht, Ziele) zur Planberechnung verarbeitet werden. Keine Weitergabe zum KI-Modelltraining.",
        "ai.loading": "Der Coach schreibt deinen Plan …",
        "ai.loadingHint": "Das dauert etwa 10–20 Sekunden.",
        "ai.error": "Der Plan konnte nicht erstellt werden: {message}",
        "ai.retry": "Nochmal versuchen",
        "ai.resultTitle": "Dein Trainingsplan",
        "ai.regenerate": "Neuen Plan erstellen",
        "ai.start": "Als Trainingsplan starten",
        "ai.started": "Trainingsplan gestartet!",
        "ai.pickDaysFirst": "Wähle mindestens einen Trainingstag.",
        "ai.notes": "Hinweise vom Coach",
        "ai.dayFocus": "Fokus",
        "ai.limitReached": "Tageslimit erreicht — morgen geht es weiter.",
        "ai.noBackend": "Der KI-Coach braucht das Supabase-Backend. Lokal ist er nicht erreichbar.",
        "tp.pickDays": "Trainingstage wählen",
        "tp.duration": "Dauer",
        "tp.weeksShort": "{n} W",
        "tp.settingsFromGenerator": "Einstellungen (aus Generator)",
        "tp.summary": "Split: {split} · {count} Übungen · {method} · {rest}s Pause",
        "tp.countHint": "{days} Tage × {cycles} Zyklen =",
        "tp.countHintStrong": "{n} unterschiedliche Pläne",
        "tp.rollPlans": "PLÄNE WÜRFELN",
        "tp.rollAgain": "Neu würfeln",
        "tp.start": "Trainingsplan starten",
        "tp.started": "Trainingsplan gestartet!",
        "tp.tapDay": "Tag antippen für alle {cycles}Pläne",
        "tp.week": "WOCHE",
        "tp.cycle": "Zyklus {n} / {total}",
        "tp.isTrainingDay": "Heute ist Trainingstag",
        "tp.noTrainingDay": "Heute kein Trainingstag",
        "tp.daysLeft": "noch {n} Tage bis Planende",
        "tp.end": "Plan beenden",
        "tp.finished": "🎉 Trainingsplan abgeschlossen!",
        "tp.finishedHint": "{n} Wochen geschafft. Zeit für einen neuen Plan.",
        "tp.newPlan": "Neuen Plan erstellen",
        "tp.today": "heute",
        "tp.daysAgo": "vor {n} Tg.",
        "tp.inDays": "in {n} Tg.",
        "tp.cycleLabel": "Zyklus {n}",
        "tp.current": "aktuell",
        "tp.plansCount": "{n} Pläne",
        "tp.planCount": "{n} Plan",
        "tp.favorite": "Als Favorit speichern",
        "saved.title": "Meine gespeicherten Pläne",
        "saved.empty": "Noch keine Pläne gespeichert.",
        "saved.emptyHint": "Erstelle im Generator einen Plan und tippe auf „Speichern“.",
        "saved.exercises": "{n} Übungen",
        "saved.load": "Laden",
        "saved.delete": "Löschen",
        "saved.workouts": "Trainingspläne",
        "saved.mealPlans": "Ernährungspläne",
        "saved.noMealPlans": "Noch keine Ernährungspläne gespeichert.",
        "ai.saveMealPlan": "Ernährungsplan speichern",
        "ai.mealPlanSaved": "Ernährungsplan gespeichert!",
        "common.all": "Alles",
        "fav.title": "Favorisierte Tagespläne",
        "fav.empty": "Noch keine Favoriten.",
        "fav.emptyHint": "Tippe im Trainingsplan-Tab auf das ❤️ neben einem Tag.",
        "fav.remove": "Entfernen",
        "fav.added": "„{day}“ zu Favoriten hinzugefügt!",
        "pro.badge": "PRO",
        "pro.gateText": "{feature} gehört zu Kraftwürfel Pro. Würfeln bleibt für alle kostenlos.",
        "pro.cta": "Pro holen",
        "pro.notUnlocked": "Dein Konto ist noch nicht freigeschaltet.",
        "pro.feature.save": "Pläne speichern",
        "pro.feature.start": "Einen Trainingsplan starten",
        "pro.feature.favorites": "Tagespläne favorisieren",
        "pro.feature.ai": "Der KI-Coach",
        "pro.feature.live": "Die Live-Session",
        "proScreen.back": "Zurück zum Würfeln",
        "proScreen.headline": "KRAFTWÜRFEL PRO",
        "proScreen.pitch": "Würfeln bleibt kostenlos. Pro schaltet unbegrenzte KI-Pläne, Speichern und 100% Werbefreiheit frei.",
        "proScreen.benefit.ai": "Unbegrenzte KI-Trainings- & Ernährungspläne (ohne Werbevideos)",
        "proScreen.benefit.ads": "100% Werbefrei (keine Banner & keine Unterbrechungen)",
        "proScreen.benefit.save": "Alle Pläne & Meal Guides dauerhaft speichern & verwalten",
        "proScreen.benefit.plans": "Beide Zyklen (Zyklus 1 & 2) frei anpassen & exportieren",
        "proScreen.benefit.watch": "Apple Watch & Sperrbildschirm Live-Tracking mit Puls",
        "proScreen.signIn": "ANMELDEN",
        "proScreen.signUp": "KONTO ERSTELLEN",
        "proScreen.email": "E-Mail",
        "proScreen.password": "Passwort",
        "proScreen.submitSignIn": "LOS GEHT'S",
        "proScreen.submitSignUp": "REGISTRIEREN",
        "proScreen.toSignUp": "Noch kein Konto? Registrieren",
        "proScreen.toSignIn": "Schon ein Konto? Anmelden",
        "proScreen.confirmMail": "Bestätigungs-E-Mail verschickt. Link anklicken, dann anmelden.",
        "proScreen.choosePlan": "Wähle deine Mitgliedschaft",
        "proScreen.monthlyPlan": "Monats-Abo",
        "proScreen.monthlyPrice": "7,99 € / Monat",
        "proScreen.monthlySub": "Jederzeit flexibel kündbar",
        "proScreen.yearlyPlan": "Jahres-Abo",
        "proScreen.yearlyPrice": "49,99 € / Jahr",
        "proScreen.yearlySub": "nur 4,16 € / Monat · Spare 48%",
        "proScreen.payNow": "Jetzt PRO aktivieren",
        "proScreen.upgradeSuccess": "🎉 Willkommen bei KRAFTWÜRFEL PRO!",
        "proScreen.terms": "Nutzungsbedingungen (EULA)",
        "proScreen.privacy": "Datenschutzerklärung",
        "proScreen.subscriptionTerms": "Die Zahlung wird bei Kaufbestätigung über deinen Apple-ID-Account abgerechnet. Das Abonnement verlängert sich automatisch, sofern die automatische Verlängerung nicht mindestens 24 Stunden vor Ablauf des aktuellen Zeitraums in den Apple-ID-Einstellungen deaktiviert wird. Du kannst dein Abonnement jederzeit in deinen Apple-ID-Account-Einstellungen verwalten und kündigen.",
        "tp.weeks": "Wochen",
        "tp.moveUp": "Workout früher in der Woche",
        "tp.moveDown": "Workout später in der Woche",
        "tp.resetPlans": "Pläne zurücksetzen",
        "ai.localFallback": "Offline erstellt aus der Vorlagen-Bibliothek — der KI-Coach war nicht erreichbar.",
        "ai.fallbackReason": "Grund: {reason}",
        "ai.customLimitations": "Einschränkungen (optional)",
        "ai.limitPlaceholder": "z. B. Knieprobleme, kein Überkopfdrücken …",
        "fav.removed": "„{day}“ aus Favoriten entfernt",
        "fav.today": "Heute",
        // Gratis ist genau ein Favorit drin — die Zahl kommt aus
        // FavoritesStore.freeLimit, damit Text und Regel nicht auseinanderlaufen.
        "fav.limitTitle": "Favoriten-Grenze erreicht",
        "fav.limitBody": "Gratis kannst du {n} Tagesplan als Favorit markieren. Mit Pro sind es beliebig viele.",
        "proScreen.checkoutPending": "Die Bezahlung ist noch nicht angebunden. Testkonten schaltet der Betreiber frei.",
        "proScreen.noEntitlement": "Für dieses Konto ist kein Pro-Zugang hinterlegt.",
        "proScreen.checkAccess": "Zugang prüfen",
        "proScreen.noBackend": "Diese Version läuft ohne Server — Anmelden ist hier nicht möglich. Trage VITE_SUPABASE_URL und VITE_SUPABASE_ANON_KEY ein und baue neu.",
        "proScreen.alreadyPro": "Pro ist für dieses Konto aktiv.",
        "live.estimated": "geschätzt",
        "settings.backend": "Verbindung",
        "settings.backendHost": "kraftwuerfel-api.onrender.com",
        "settings.online": "Erreichbar · {n} Übungen",
        "settings.offline": "Nicht erreichbar: {reason}",
        "settings.checking": "Wird geprüft …",
        "settings.unknown": "Noch nicht geprüft",
        "settings.catalogServer": "Katalog vom Server · {n} Übungen",
        "settings.catalogBundled": "Eingebauter Katalog · {n} Übungen",
        "settings.catalogHint": "Neue Übungen kommen ohne App-Update an.",
        "settings.aiServer": "KI-Pläne kommen vom Server",
        "settings.aiLocal": "KI-Pläne werden lokal erzeugt",
        "settings.aiLocalHint": "Melde dich an, damit der Server die Pläne rechnet.",
        "settings.checkConnection": "Verbindung prüfen",
        "ai.goalWeight": "Zielgewicht",
        "ai.goalWeightNone": "Kein Ziel gesetzt — der Rahmen richtet sich nach deinem Trainingsziel.",
        "ai.goalWeightHold": "Gewicht halten.",
        "ai.goalWeightLose": "{kg} kg abnehmen — der Plan rechnet mit einem Defizit.",
        "ai.goalWeightGain": "{kg} kg zunehmen — der Plan rechnet mit einem Überschuss.",
        "ai.goalWeightClear": "Ziel entfernen",
        "settings.title": "Einstellungen",
        "settings.account": "Konto",
        "settings.language": "Sprache",
        "settings.pro": "Pro",
        "settings.proActive": "Pro ist aktiv",
        "settings.proInactive": "Pro ist nicht aktiv",
        "settings.proHint": "Der KI-Coach, Speichern und Favoriten gehören zu Pro.",
        "settings.restorePurchases": "Käufe wiederherstellen",
        "settings.legal": "Rechtliches",
        "legal.imprint": "Impressum",
        "legal.privacy": "Datenschutz",
        "legal.placeholderWarning": "Dieser Text ist noch ein Gerüst. Die Angaben in spitzen Klammern müssen vor der Veröffentlichung durch die echten Daten des Betreibers ersetzt werden (LegalView.swift).",
        "auth.title": "Konto",
        "auth.signIn": "Anmelden",
        "auth.signUp": "Registrieren",
        "auth.signOut": "Abmelden",

        // Kontolöschung nach Art. 17 DSGVO. Der Text sagt ausdrücklich, WAS
        // verschwindet — „Konto löschen“ allein lässt offen, ob die
        // gespeicherten Pläne bleiben.
        "auth.deleteAccount": "Konto löschen",
        "auth.deleteAccountHint": "Löscht dein Konto und alle Daten endgültig",
        "auth.deleteConfirmTitle": "Konto endgültig löschen?",
        "auth.deleteConfirmBody": "Dein Konto, alle gespeicherten Pläne, Favoriten, Meal Guides und deine Körperdaten werden gelöscht. Das lässt sich nicht rückgängig machen.",
        "auth.deleteConfirmAction": "Löschen",
        "auth.deleteCancel": "Abbrechen",
        "auth.deleteDoneTitle": "Konto gelöscht",
        "auth.deleteDoneBody": "Dein Konto und alle zugehörigen Daten sind entfernt. Würfeln kannst du weiterhin ohne Konto.",
        "auth.deleteFailedTitle": "Löschung fehlgeschlagen",
        "auth.deleteFailedBody": "Es wurde nichts gelöscht — dein Konto besteht weiter. Grund: {reason}. Versuch es später erneut oder schreib uns an appoint.20@gmail.com.",
        "auth.deleteNoSession": "Keine aktive Sitzung — bitte neu anmelden.",
        "auth.deleteNotSupported": "Der Server nimmt Löschanfragen noch nicht entgegen",
        "auth.signInOrUp": "Anmelden oder registrieren",
        "auth.signedIn": "Angemeldet",
        "auth.email": "E-Mail",
        "auth.password": "Passwort",
        "auth.whyAccount": "Mit Konto erzeugt der KI-Coach die Pläne auf dem Server statt auf dem Gerät.",
        "auth.hintSignIn": "Ohne Konto funktioniert die App weiter — der KI-Coach rechnet dann lokal.",
        "auth.hintSignUp": "Mindestens sechs Zeichen. Je nach Einstellung des Dienstes musst du deine E-Mail-Adresse anschließend bestätigen.",
        "auth.confirmEmail": "Fast fertig: Bestätige den Link in der E-Mail, dann kannst du dich anmelden.",
        "auth.invalidInput": "Bitte eine gültige E-Mail-Adresse und mindestens sechs Zeichen als Passwort.",
        "auth.notConfigured": "Die Anmeldung ist auf dem Server noch nicht eingerichtet. Bitte später erneut versuchen.",
        "auth.invalidCredentials": "E-Mail oder Passwort ist falsch.",
        "auth.tooManyAttempts": "Zu viele Versuche. Warte einen Moment und probiere es noch einmal.",
        "auth.serverError": "Server nicht erreichbar: {reason}",
        "saved.tabWorkouts": "Workouts",
        "saved.tabAIPlans": "KI-Pläne",
        "saved.tabMealGuides": "Meal Guides",
        "saved.emptyWorkouts": "Noch keine Workouts gespeichert",
        "saved.emptyAIPlans": "Noch keine KI-Pläne gespeichert",
        "saved.emptyMealGuides": "Noch keine Meal Guides gespeichert",
        "saved.emptyAIPlansHint": "Erzeuge einen Plan im KI-Coach und speichere ihn dort.",
        "saved.emptyMealGuidesHint": "Der Meal Guide entsteht zusammen mit einem KI-Plan.",
        "saved.saveFailed": "Nicht gespeichert",
        "saved.open": "Öffnen",
        "saved.close": "Schließen",
        "exercise.imageHint": "Tippen zeigt das Bild groß",
        "saved.days": "{n} Tage",
        "saved.weeks": "{n} Wochen",
        "meal.perDay": "kcal / Tag",
        "meal.protein": "Eiweiß",
        "meal.carbs": "Kohlenhydrate",
        "meal.fat": "Fett",
        "meal.timing": "Mahlzeiten-Timing",
        "meal.shakes": "Power-Shakes & Supplemente",
        "meal.shakeTag": "Shake",
        "meal.save": "Meal Guide speichern",
        "meal.savedTitle": "Gespeichert",
        "meal.savedBody": "Der Meal Guide liegt jetzt unter GESPEICHERT → Meal Guides.",
        "meal.failedTitle": "Nicht gespeichert",
        "meal.failedBody": "Der Meal Guide konnte nicht abgelegt werden. {reason}",
        "meal.alreadySaved": "Schon gespeichert",
        "meal.notes": "Hinweise",
        "meal.generateFailed": "Der Meal Guide konnte nicht erstellt werden. Bitte versuche es erneut.",
        "meal.regenerate": "Meal Guide erstellen",
        "meal.day": "Tag",
        "meal.addFood": "+ Zutat hinzufügen",
        "meal.addFoodTitle": "Zutat / Nahrungsmittel hinzufügen",
        "meal.foodName": "Lebensmittel / Name",
        "meal.foodAmount": "Menge / Portion (z. B. 100g)",
        "meal.foodCalories": "Kalorien (kcal)",
        "meal.saveChanges": "Änderungen speichern",
        "meal.changesSaved": "Änderungen erfolgreich gespeichert",
        "meal.shakeTitle": "Protein-Shake & Einnahme",
        "meal.shakePowder": "Pulvermenge",
        "meal.shakeLiquid": "Flüssigkeit",
        "meal.shakeTiming": "Einnahme-Zeitpunkt",
        "ai.tabWorkout": "Trainingsplan",
        "ai.tabNutrition": "Meal Guide",
        "ai.cycleActive": "Aktiv",
        "ai.savePlan": "Plan speichern",
        "ai.planSavedTitle": "Gespeichert",
        "ai.planSavedBody": "Der Plan liegt jetzt unter GESPEICHERT → KI-Pläne.",
        "ai.planFailedTitle": "Nicht gespeichert",
        "ai.planFailedBody": "Der Plan konnte nicht abgelegt werden. {reason}",
        "ai.planAlreadySaved": "Schon gespeichert",
        "ai.newPlan": "Neuen Plan konfigurieren",
        "ai.badResponse": "unbrauchbare Antwort",
        "ai.warmupSection": "Aufwärmen",
        "live.sourceWatch": "Apple Watch",
        "live.avg": "Ø",
        "live.peak": "Max",
        "live.duration": "Dauer",
        "live.connectSensor": "Pulssensor koppeln",
        "live.estimatedNote": "Puls und Kalorien sind Schätzwerte aus einem Modell. Koppel einen Sensor für echte Messwerte.",
        "live.noSensorTitle": "KEIN SENSOR VERBUNDEN",
        "live.noSensorBody": "Verbinde eine Apple Watch oder einen Brustgurt mit der App — dann siehst du hier, wie dein Körper das heutige Training aufnimmt.",
        "ai.warmupTitle": "Aufwärmen",
        "ai.warmup.auto": "Coach entscheidet",
        "ai.warmup.yes": "Ja, immer",
        "ai.warmup.no": "Nein, danke",
        "ai.warmupHint.auto": "nach Alter und Erfahrung",
        "ai.warmupHint.yes": "jeder Tag mit Aufwärmteil",
        "ai.warmupHint.no": "direkt zur ersten Übung",
        "ai.warmupLabel": "Aufwärmen",
        "ai.dietTitle": "Ernährungsform",
        "ai.diet.omnivore": "Ich esse alles",
        "ai.diet.vegetarian": "Vegetarisch",
        "ai.diet.lacto_vegetarian": "Lakto-Vegetarisch",
        "ai.diet.vegan": "Vegan",
        "ai.workoutTab": "Trainingsplan",
        "ai.mealGuideTab": "Meal Guide",
        "ai.nutritionTitle": "Ernährungsplan & Meal Guide",
        "ai.perDay": "Tag",
        "ai.protein": "Eiweiß",
        "ai.carbs": "Kohlenhydrate",
        "ai.fat": "Fett",
        "ai.shakes": "Protein-Shakes",
        "ai.nutritionDisclaimer": "Richtwerte auf Basis deiner Angaben, keine Ernährungsberatung. Bei Vorerkrankungen, Medikamenten oder in Schwangerschaft und Stillzeit vorher ärztlich abklären.",
        "live.set": "Satz",
        "live.restOverBody": "Pause vorbei — weiter geht's!",
        "music.title": "Gym-Musik",
        "music.close": "Schließen",
        "music.offline": "Offline-Mediathek",
        "music.streaming": "Streaming",
        "music.add": "Titel aus Apple Music / Mediathek importieren",
        "music.importing": "Titel werden importiert…",
        "music.remove": "Aus Playlist entfernen",
        "music.prev": "Vorheriger Titel",
        "music.next": "Nächster Titel",
        "music.playPause": "Abspielen / Pause",
        "music.emptyTitle": "Noch keine Musik gespeichert",
        "music.emptyText": "Füge MP3- oder M4A-Dateien von deinem Gerät hinzu. Sie bleiben gespeichert und laufen im Gym auch ohne Empfang.",
        "music.usage": "{n} Titel · {size} auf diesem Gerät",
        "music.noStorage": "Dieser Browser kann keine Musik offline speichern.",
        "music.lockScreenHint": "Läuft weiter, wenn das Display aus ist — Titel und aktuelle Übung erscheinen auf dem Sperrbildschirm und auf der Apple Watch.",
        "music.consentTitle": "Streaming lädt externe Inhalte",
        "music.consentText": "Spotify und YouTube setzen eigene Cookies und sehen deine IP-Adresse, sobald der Player lädt. Offline-Musik funktioniert ohne das.",
        "music.consentAccept": "Verstanden, Streaming laden",
        "music.closeStream": "Player schließen",
        "music.needsInternet": "braucht Internet",

        // Spotify wird nicht per SDK eingebunden, sondern per Deep-Link
        // geöffnet — kein Entwicklerkonto, kein Client-Secret nötig. Die
        // Playlist wählt der Nutzer drüben in Spotify.
        "music.spotifyTitle": "Spotify",
        "music.spotifyHint": "Öffnet Spotify — dort tippst du deine Playlist an, sie läuft weiter, während du trainierst.",
        "music.spotifyOpen": "Spotify öffnen",
        "music.spotifyBrowseWorkout": "Workout-Playlists durchsuchen",
        "music.spotifyNotInstalled": "Spotify ist nicht installiert — der Knopf öffnet stattdessen den Browser.",
        "common.loading": "Lädt…",
        "common.cancel": "Abbrechen",
        "common.search": "Übung suchen…",
        "live.title": "LIVE-TRAINING",
        "live.exerciseOf": "Übung {current} von {total}",
        "live.setOf": "Satz {current} von {total}",
        "live.repsTarget": "{reps} Wdh.",
        "live.rest": "PAUSE",
        "live.paused": "PAUSIERT",
        "live.pauseSession": "Training pausieren",
        "live.resumeSession": "Training fortsetzen",
        "live.weight": "GEWICHT",
        "live.reps": "WDH.",
        "live.last": "LETZTES",
        "live.target": "ZIEL",
        "live.completeSet": "SATZ ABHAKEN",
        "live.saveSet": "SATZ {n} SPEICHERN",
        "live.addRest": "+30 s Pause",
        "live.skipRest": "Pause beenden",
        "live.skipExercise": "Übung überspringen",
        "live.nextExercise": "Nächste Übung",
        "live.upNext": "ALS NÄCHSTES",
        "live.deferred": "SPÄTER",
        "live.modeFocus": "Fokus",
        "live.modeLog": "Satz-Protokoll",
        "live.endSession": "Training beenden",
        "live.confirmEnd": "Möchtest du das Training wirklich beenden?",
        "live.finished": "🎉 TRAINING BEENDET!",
        "live.finishedSub": "Starke Leistung! Dein Training ist im Kasten.",
        "live.totalTime": "GESAMTZEIT",
        "live.totalSets": "SÄTZE GESCHAFFT",
        "live.totalExercises": "ÜBUNGEN",
        "live.close": "Fertig & Schließen",
        "live.startTraining": "TRAINING STARTEN",
        "live.calories": "kcal",
        "live.caloriesBurned": "Kalorien",
        "live.heartRate": "Puls",
        "live.avgHeartRate": "DURCHSCHNITT",
        "live.peakHeartRate": "MAX. PULS",
        "live.volume": "Volumen",
        "live.totalVolume": "GESAMTVOLUMEN",
        "live.connectWatch": "Sensor / Watch verbinden",
        "live.connected": "Verbunden",
        "live.notConnected": "Live-Schätzung",
        "live.appleHealthSync": "Apple Health aktiv",
        "live.exportHealth": "In Apple Health sichern",
        "live.zone1": "Regeneration",
        "live.zone2": "Fettverbrennung",
        "live.zone3": "Aerob",
        "live.zone4": "Anaerob",
        "live.zone5": "Maximal",
        "ai.biometricsTitle": "Körper & Physis",
        "ai.sex": "Geschlecht",
        "ai.sexMale": "Männlich",
        "ai.sexFemale": "Weiblich",
        "ai.sexOther": "Divers",
        "ai.age": "Alter",
        "ai.height": "Größe (cm)",
        "ai.weight": "Gewicht (kg)",
        "ai.years": "Jahre",
        "ai.step": "Schritt {current} von {total}",
        "ai.next": "WEITER",
        "ai.back": "Zurück",
        "ai.review": "Übersicht & Start",
        "ai.reviewSummary": "Dein Profil im Überblick",
        "ai.quickLimitations": "Häufige Einschränkungen",
        "ai.limitNone": "Keine Einschränkungen",
        "ai.limitKnee": "Knie schonen",
        "ai.limitShoulder": "Schulter schonen",
        "ai.limitOverhead": "Kein Überkopfdrücken",
        "ai.limitBack": "Unterer Rücken schonen",
        "ai.limitWrists": "Handgelenke schonen",
        "live.lockScreenCard": "Live Activity / Sperrbildschirm",
        "live.watchMode": "Apple Watch Controller",
        "live.wakeLockActive": "Fokus aktiv · Display bleibt an",
        "crash.title": "DA IST WAS SCHIEFGELAUFEN",
        "crash.text": "Die App ist auf einen unerwarteten Fehler gestoßen. Neu laden hilft meistens — gespeicherte Pläne bleiben erhalten.",
        "crash.reload": "NEU LADEN",
        "local.title": "Lokaler Modus:",
        "local.text": "Ohne Verbindung zum Dienst bleiben Pläne nur auf diesem Gerät und der KI-Coach ist nicht erreichbar.",

        "ai.somatotypeTitle": "KÖRPERTYP",
        "ai.activityTitle": "ALLTAG & LEBENSSTIL",
        "ai.pushups": "Liegestütze am Stück",
        "ai.pullups": "Klimmzüge am Stück",
        "ai.plank": "Plank halten",

        "ai.equipmentAllHint": "Volles Studio-Equipment",
        "challenge.wantTitle": "HOME-CHALLENGE",
        "challenge.wantText": "Eine mehrtägige Challenge für zu Hause, ohne Studio. Willst du eine? Wenn nicht, überspringen wir die Fragen dazu — du kannst sie jederzeit in den Einstellungen nachholen.",
        "challenge.wantYes": "Ja, einrichten",
        "challenge.wantNo": "Nein, danke",
        "challenge.disabledTitle": "Home-Challenge ist aus",
        "challenge.disabledText": "Du hast die Challenge im Fragebogen abgewählt. Schalte sie in deinem Profil ein, um eine zu starten.",

        "dayEdit.title": "TAG ANPASSEN",
        "dayEdit.edit": "Anpassen",
        "dayEdit.reroll": "Neu würfeln",
        "dayEdit.replace": "Tauschen",
        "dayEdit.remove": "Entfernen",
        "dayEdit.add": "Übung hinzufügen",
        "dayEdit.shuffleDay": "Tag neu mischen",

        "planSetup.title": "PLAN-AUFBAU",
        "planSetup.subtitle": "Split, Methode, Umfang & Zyklen",
        "planSetup.cycles": "ZYKLEN",
        "planSetup.activeNote": "Der laufende Plan behält seine Übungen. Diese Auswahl gilt für den nächsten Plan — einzelne Tage änderst du direkt am Tag über „Anpassen“.",

        "saved.setActive": "Als Plan starten",
        "saved.setActiveTitle": "ALS TRAININGSPLAN STARTEN",
        "saved.setActiveBody": "„{name}“ wird dein laufender Trainingsplan. Du verfolgst ihn dann im Trainingsplan-Tab mit Wochen und Zyklen.",
        "saved.setActiveReplace": "„{name}“ ersetzt deinen laufenden Trainingsplan. Der bisherige Fortschritt geht dabei verloren.",

        "ai.gateTitle": "{done} von {total} Videos gesehen",
        "ai.gateText": "Der KI-Coach ist eine Pro-Funktion. Kostenlos schaltest du je einen Plan mit kurzen Videos frei — das gilt auch für jeden weiteren Plan.",
        "ai.gateWatch": "VIDEO ANSEHEN",
        "ai.gateSkipWithPro": "Mit Pro ohne Videos — jederzeit",

        // Anmeldeschranke beim Start
        "gate.title": "WILLKOMMEN",
        "gate.subtitle": "Melde dich an, um deine Pläne, Fortschritte und den KI-Coach auf allen Geräten zu behalten.",
        "gate.signUp": "KONTO ERSTELLEN",
        "gate.signIn": "ANMELDEN",
        "gate.why": "Warum ein Konto?",
        "gate.whyText": "Deine Trainingspläne, dein Fortschritt und dein Pro-Abo hängen am Konto — nicht am Gerät.",

        // Fragebogen nach der Registrierung
        "onboarding.welcomeTitle": "PLÄNE, DIE ZU DIR PASSEN",
        "onboarding.welcomeText": "Mit ein paar Angaben zu Körper, Ziel und Ausrüstung baut dir der Coach Pläne, die wirklich zu dir passen. Das dauert zwei Minuten — du kannst es aber auch später nachholen.",
        "onboarding.setupProfile": "PROFIL EINRICHTEN",
        "onboarding.jumpIn": "DIREKT LOSLEGEN",
        "onboarding.laterHint": "Du kannst dein Profil jederzeit in den Einstellungen nachtragen.",
        "onboarding.start": "LOS GEHT'S",
        "onboarding.later": "Später ausfüllen",
        "onboarding.step": "Schritt {current} von {total}",
        "onboarding.next": "WEITER",
        "onboarding.back": "Zurück",
        "onboarding.finish": "FERTIG",
        "onboarding.titleBody": "Dein Körper",
        "onboarding.titleGoal": "Dein Ziel",
        "onboarding.titleTraining": "Dein Training",
        "onboarding.titleChallenge": "Deine Home-Challenge",
        "onboarding.titleNutrition": "Ernährung & Einschränkungen",
        "onboarding.titleHealth": "Apple Health",
        "onboarding.doneTitle": "ALLES KLAR",
        "onboarding.doneText": "Dein Profil steht. Du kannst jeden Wert jederzeit in den Einstellungen ändern.",

        // Apple Health
        "health.title": "Mit Apple Health verbinden",
        "health.text": "Kraftwürfel übernimmt Gewicht, Größe und Körperdaten aus Health, damit du sie nicht eintippen musst — und sichert abgeschlossene Trainings dorthin zurück.",
        "health.readTitle": "Wird gelesen",
        "health.readItems": "Herzfrequenz, Gewicht, Größe, Körperfettanteil, Geburtsdatum",
        "health.writeTitle": "Wird geschrieben",
        "health.writeItems": "Gewicht, Körperfettanteil, abgeschlossene Trainings",
        "health.estimateNote": "Geschätzte Werte werden nie nach Health geschrieben — nur Gemessenes und deine eigenen Angaben.",
        "health.connect": "VERBINDEN",
        "health.skip": "Ohne Health fortfahren",
        "health.connected": "Verbunden",
        "health.unavailable": "Auf diesem Gerät nicht verfügbar",
        "health.prefilled": "{count} Angaben aus Health übernommen",
        "health.nothingRead": "Keine Werte übernommen — du kannst sie gleich selbst eintragen.",

        // Profil in den Einstellungen
        "settings.profile": "Dein Profil",
        "profile.title": "DEIN PROFIL",
        "profile.subtitle": "Diese Angaben nutzen KI-Coach und Home-Challenge. Änderungen wirken sofort auf den nächsten Plan.",
        "profile.sectionBody": "KÖRPER",
        "profile.sectionGoal": "ZIEL & ERFAHRUNG",
        "profile.sectionTraining": "TRAINING",
        "profile.sectionChallenge": "HOME-CHALLENGE",
        "profile.sectionNutrition": "ERNÄHRUNG",
        "profile.sectionHealth": "APPLE HEALTH",
        "profile.incompleteTitle": "Profil noch nicht ausgefüllt",
        "profile.incompleteText": "Beantworte den Fragebogen einmal, dann erstellt der Coach deinen Plan ohne weitere Fragen.",
        "profile.incompleteCta": "FRAGEBOGEN AUSFÜLLEN",
        "profile.shakesTitle": "Protein-Shakes",
        "profile.shakesLabel": "Ich trinke Shakes",
        "profile.shakesHint": "Nur dafür da: Wir erinnern dich 30 Minuten nach dem Training daran. Aus, wenn du keine trinkst.",
        "profile.limitations": "Wünsche & Einschränkungen für den Coach (optional)",
        "profile.limitationsHint": "z. B. „empfindliche Knie, keine Sprünge, kurze Pausen bitte“",
        "profile.selfAssessment": "SELBSTEINSCHÄTZUNG",

        // Ein-Tipp-Erzeugung
        "ready.profileTitle": "DEIN PROFIL",
        "ready.edit": "Ändern",
        "ready.generateCoach": "PLAN ERSTELLEN",
        "ready.generateChallenge": "CHALLENGE STARTEN",
        "ready.coachText": "Der Coach baut deinen Plan aus den Angaben in deinem Profil.",
        "ready.challengeText": "Deine Challenge entsteht aus den Angaben in deinem Profil.",
    ]

    static let en: [String: String] = [
        "music.emptyTextNative": "Pick tracks from your library. Songs downloaded from Apple Music play without a connection.",
        "music.denied": "Without access to your library the app cannot play music. You can allow it in Settings.",
        "app.subtitle": "Smart Plan & AI Coach",
        "greeting.title": "Hello, {name}!",
        "greeting.guestName": "Athlete",
        "greeting.coachBadge": "AI COACH",
        "greeting.sentence": "Ready for your next workout?",
        "greeting.sentence.1": "Ready for today, {name}?",
        "greeting.sentence.2": "{name}, time to lift.",
        "greeting.sentence.3": "Let's go, {name}!",
        "greeting.sentence.4": "Your workout awaits, {name}.",
        "greeting.sentence.5": "Bring the energy today, {name}.",
        "greeting.sentence.6": "{name}, let's get started.",
        "greeting.sentence.7": "Focus mode activated, {name}.",
        "greeting.sentence.8": "Every rep counts, {name}.",
        "greeting.sentence.9": "Time to break your personal records, {name}.",
        "greeting.sentence.10": "Stronger than yesterday, {name}.",
        "greeting.sentence.11": "{name}, conquer your limits today!",
        "greeting.sentence.12": "Discipline beats motivation, {name}.",
        "greeting.sentence.13": "Make today count, {name}.",
        "greeting.sentence.14": "Your muscles are waiting, {name}.",
        "greeting.sentence.15": "No excuses, just pure results, {name}.",
        "greeting.sentence.16": "{name}, let's make that iron work.",
        "greeting.sentence.17": "Growth happens outside your comfort zone, {name}.",
        "greeting.sentence.18": "Eyes on the goal, mind on the reps, {name}.",
        "greeting.sentence.19": "{name}, unlock your full potential today!",
        "greeting.sentence.20": "A strong mind in a strong body, {name}.",
        "greeting.sentence.21": "Success is the sum of daily efforts, {name}.",
        "greeting.sentence.22": "{name}, turn this session into a masterpiece.",
        "greeting.sentence.23": "Full concentration on every single rep, {name}.",
        "greeting.sentence.24": "Stay consistent, {name} – it always pays off!",
        "greeting.sentence.25": "Welcome back to the growth zone, {name}.",
        "auth.nameLabel": "YOUR FIRST NAME / NAME",
        "auth.namePlaceholder": "e.g. Alex",
        "auth.emailLabel": "EMAIL",
        "auth.passwordLabel": "PASSWORD",
        "auth.passwordConfirmLabel": "CONFIRM PASSWORD",
        "auth.passwordsDoNotMatch": "Passwords do not match.",
        "auth.createAccountHeader": "CREATE ACCOUNT",
        "auth.signInHeader": "SIGN IN",
        "auth.toSignInPrompt": "Already have an account? Sign in",
        "auth.toSignUpPrompt": "Don't have an account? Sign up",
        "auth.forgotPassword": "Forgot password?",
        "auth.forgotPasswordHeader": "RESET PASSWORD",
        "auth.forgotPasswordHint": "Enter your email address. We'll send you a link to reset your password.",
        "auth.resetPasswordSubmit": "SEND RESET LINK",
        "auth.resetPasswordSent": "If an account exists with this email, a reset link has been sent. Please check your inbox.",
        "auth.backToSignIn": "Back to sign in",
        "proScreen.restorePurchases": "Restore purchases",
        "proScreen.featureTitle": "All Pro benefits at a glance",
        "proScreen.badge": "PREMIUM",
        "proScreen.billedYearly": "billed annually",
        "proScreen.billedMonthly": "billed monthly",
        "proScreen.subscribeNow": "Activate PRO Now",
        "proScreen.secureCheckout": "Secure checkout via Apple In-App Purchase",
        "method.standard": "3×3×3",
        "method.standardLong": "3×3×3 Method",
        "tabs.generator": "GENERATOR",
        "tabs.trainingsplan": "TRAINING PLAN",
        "tabs.plans": "PLANS",
        "tabs.progress": "PROGRESS",
        "tabs.saved": "SAVED",
        "tabs.favorites": "FAVOURITES",
        "tabs.ai": "AI COACH",
        "nav.getPro": "GET PRO",
        "nav.signOut": "Sign out",
        "mode.dice": "Roll",
        "mode.ai": "AI coach",
        "mode.aiBadge": "PRO",
        "gen.split": "Choose split",
        "gen.muscles": "Muscle groups",
        "gen.count": "Number of exercises",
        "gen.method": "Training method",
        "gen.rest": "Rest per set",
        "gen.roll": "ROLL",
        "gen.remix": "Reshuffle the whole plan",
        "gen.rerollOne": "Roll again",
        "gen.sets": "Sets",
        "gen.reps": "Reps",
        "gen.restShort": "Rest",
        "gen.namePlaceholder": "Name, e.g. Current plan",
        "gen.save": "Save",
        "gen.empty": "No plan rolled yet.",
        "gen.emptyHint": "Pick a split and tap “ROLL”.",
        "gen.savedAs": "“{name}” saved!",
        "gen.defaultName": "Plan from {date}",
        "ai.title": "Your plan, built by AI",
        "ai.intro": "A few questions — the AI coach turns them into a training plan that fits you.",
        "ai.goal": "Goal",
        "ai.goal.muscle": "Build muscle",
        "ai.goal.strength": "Maximal strength",
        "ai.goal.definition": "Get lean",
        "ai.goal.fitness": "General fitness",
        "ai.goal.abnehmen": "Weight Loss & Fat Burning",
        "ai.experience": "Experience",
        "ai.experience.beginner": "Beginner",
        "ai.experience.intermediate": "Intermediate",
        "ai.experience.advanced": "Advanced",
        "ai.exp.beginner": "Beginner",
        "ai.exp.intermediate": "Intermediate",
        "ai.exp.advanced": "Advanced",
        "ai.days": "Training days",
        "ai.duration": "Session length",
        "ai.minutes": "{n} min",
        "ai.equipment": "Available equipment",
        "ai.equipmentAll": "Everything",
        "ai.focus": "Focus (optional)",
        "ai.limitations": "Limitations (optional)",
        "ai.limitationsPlaceholder": "e.g. knee issues, no overhead pressing, disc injury …",
        "ai.weeks": "Plan length",
        "ai.weeksValue": "{n} weeks",
        "ai.submit": "CREATE AI PLAN",
        "ai.videoUnlockTitle": "Unlock for Free",
        "ai.videoUnlockDesc": "Watch 3 short videos to generate your AI plan for free. Or upgrade to Pro for unlimited, ad-free plans.",
        "ai.videoUnlockButton": "Watch Video ({current}/{total})",
        "ai.videoUnlocked": "Unlocked!",
        "ai.savingIsProFeature": "Saving plans permanently to your library is a Pro feature.",
        "ai.savingMealIsProFeature": "Saving meal guides permanently is a Pro feature.",
        "ads.sponsored": "Ad",
        "ads.removeAds": "NO ADS",
        "ai.errorTitle": "The coach is taking a breather",
        "ai.errorOffline": "Can't reach him — usually that's the connection. Your answers are still here, give it another go.",
        "ai.errorGarbled": "He fumbled that one and sent back nothing usable. One more try almost always does it.",
        "ai.errorLimit": "He's built enough plans for today. He'll be back tomorrow.",
        "ai.errorSignedOut": "Your session expired. Sign in again and you're good to go.",
        "ai.privacyConsentNotice": "By creating a plan, you consent to processing your body and fitness data (height, weight, goals) for plan generation. Not used for AI model training.",
        "ai.loading": "The coach is writing your plan …",
        "ai.loadingHint": "This takes about 10–20 seconds.",
        "ai.error": "The plan could not be created: {message}",
        "ai.retry": "Try again",
        "ai.resultTitle": "Your training plan",
        "ai.regenerate": "Create a new plan",
        "ai.start": "Start as training plan",
        "ai.started": "Training plan started!",
        "ai.pickDaysFirst": "Pick at least one training day.",
        "ai.notes": "Notes from the coach",
        "ai.dayFocus": "Focus",
        "ai.limitReached": "Daily limit reached — try again tomorrow.",
        "ai.noBackend": "The AI coach needs the Supabase backend. It is unreachable in local mode.",
        "tp.pickDays": "Choose training days",
        "tp.duration": "Length",
        "tp.weeksShort": "{n} w",
        "tp.settingsFromGenerator": "Settings (from the generator)",
        "tp.summary": "Split: {split} · {count} exercises · {method} · {rest}s rest",
        "tp.countHint": "{days} days × {cycles} cycles =",
        "tp.countHintStrong": "{n} distinct plans",
        "tp.rollPlans": "ROLL PLANS",
        "tp.rollAgain": "Roll again",
        "tp.start": "Start training plan",
        "tp.started": "Training plan started!",
        "tp.tapDay": "Tap a day for all {cycles}plans",
        "tp.week": "WEEK",
        "tp.cycle": "Cycle {n} / {total}",
        "tp.isTrainingDay": "Today is a training day",
        "tp.noTrainingDay": "No training today",
        "tp.daysLeft": "{n} days left",
        "tp.end": "End plan",
        "tp.finished": "🎉 Training plan complete!",
        "tp.finishedHint": "{n} weeks done. Time for a new plan.",
        "tp.newPlan": "Create a new plan",
        "tp.today": "today",
        "tp.daysAgo": "{n} d ago",
        "tp.inDays": "in {n} d",
        "tp.cycleLabel": "Cycle {n}",
        "tp.current": "current",
        "tp.plansCount": "{n} plans",
        "tp.planCount": "{n} plan",
        "tp.favorite": "Save as favourite",
        "saved.title": "My saved plans",
        "saved.empty": "No plans saved yet.",
        "saved.emptyHint": "Build a plan in the generator and tap “Save”.",
        "saved.exercises": "{n} exercises",
        "saved.load": "Load",
        "saved.delete": "Delete",
        "saved.workouts": "Workouts",
        "saved.mealPlans": "Meal Guides",
        "saved.noMealPlans": "No meal guides saved yet.",
        "ai.saveMealPlan": "Save Meal Guide",
        "ai.mealPlanSaved": "Meal guide saved!",
        "common.all": "All",
        "fav.title": "Favourite day plans",
        "fav.empty": "No favourites yet.",
        "fav.emptyHint": "Tap the ❤️ next to a day in the training plan tab.",
        "fav.remove": "Remove",
        "fav.added": "“{day}” added to favourites!",
        "pro.badge": "PRO",
        "pro.gateText": "{feature} is part of Kraftwürfel Pro. Rolling stays free for everyone.",
        "pro.cta": "Get Pro",
        "pro.notUnlocked": "Your account is not unlocked yet.",
        "pro.feature.save": "Saving plans",
        "pro.feature.start": "Starting a training plan",
        "pro.feature.favorites": "Favouriting day plans",
        "pro.feature.ai": "The AI coach",
        "pro.feature.live": "The live session",
        "proScreen.back": "Back to rolling",
        "proScreen.headline": "KRAFTWÜRFEL PRO",
        "proScreen.pitch": "Rolling stays free. Pro unlocks unlimited AI plans, saving and 100% ad-free workouts.",
        "proScreen.benefit.ai": "Unlimited AI workout & nutrition plans (without watching ads)",
        "proScreen.benefit.ads": "100% Ad-Free (no banners & no workout interruptions)",
        "proScreen.benefit.save": "Save and manage all plans & meal guides permanently",
        "proScreen.benefit.plans": "Customize & export both training cycles freely",
        "proScreen.benefit.watch": "Apple Watch & Lock Screen live tracking with heart rate",
        "proScreen.signIn": "SIGN IN",
        "proScreen.signUp": "CREATE ACCOUNT",
        "proScreen.email": "Email",
        "proScreen.password": "Password",
        "proScreen.submitSignIn": "LET'S GO",
        "proScreen.submitSignUp": "SIGN UP",
        "proScreen.toSignUp": "No account yet? Sign up",
        "proScreen.toSignIn": "Already have an account? Sign in",
        "proScreen.confirmMail": "Confirmation email sent. Click the link, then sign in.",
        "proScreen.choosePlan": "Choose your plan",
        "proScreen.monthlyPlan": "Monthly Plan",
        "proScreen.monthlyPrice": "$7.99 / month",
        "proScreen.monthlySub": "Cancel anytime",
        "proScreen.yearlyPlan": "Yearly Plan",
        "proScreen.yearlyPrice": "$49.99 / year",
        "proScreen.yearlySub": "only $4.16 / month · Save 48%",
        "proScreen.payNow": "Activate PRO now",
        "proScreen.upgradeSuccess": "🎉 Welcome to KRAFTWÜRFEL PRO!",
        "proScreen.terms": "Terms of Use (EULA)",
        "proScreen.privacy": "Privacy Policy",
        "proScreen.subscriptionTerms": "Payment will be charged to your Apple ID account at confirmation of purchase. Subscription automatically renews unless auto-renew is turned off at least 24 hours before the end of the current period. You can manage and cancel your subscriptions in your Apple ID Account Settings at any time.",
        "tp.weeks": "weeks",
        "tp.moveUp": "Move workout earlier in the week",
        "tp.moveDown": "Move workout later in the week",
        "tp.resetPlans": "Reset plans",
        "ai.localFallback": "Built offline from the template library — the AI coach was unreachable.",
        "ai.fallbackReason": "Reason: {reason}",
        "ai.customLimitations": "Limitations (optional)",
        "ai.limitPlaceholder": "e.g. knee issues, no overhead pressing …",
        "fav.removed": "“{day}” removed from favourites",
        "fav.today": "Today",
        "fav.limitTitle": "Favourite limit reached",
        "fav.limitBody": "The free plan lets you favourite {n} day plan. Pro lifts the limit entirely.",
        "proScreen.checkoutPending": "Checkout is not connected yet. Test accounts are unlocked by the operator.",
        "proScreen.noEntitlement": "No Pro access is on file for this account.",
        "proScreen.checkAccess": "Check access",
        "proScreen.noBackend": "This build runs without a server, so signing in is not possible. Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY and rebuild.",
        "proScreen.alreadyPro": "Pro is active on this account.",
        "live.estimated": "estimated",
        "settings.backend": "Connection",
        "settings.backendHost": "kraftwuerfel-api.onrender.com",
        "settings.online": "Reachable · {n} exercises",
        "settings.offline": "Not reachable: {reason}",
        "settings.checking": "Checking …",
        "settings.unknown": "Not checked yet",
        "settings.catalogServer": "Catalogue from server · {n} exercises",
        "settings.catalogBundled": "Built-in catalogue · {n} exercises",
        "settings.catalogHint": "New exercises arrive without an app update.",
        "settings.aiServer": "AI plans come from the server",
        "settings.aiLocal": "AI plans are generated locally",
        "settings.aiLocalHint": "Sign in so the server generates the plans.",
        "settings.checkConnection": "Check connection",
        "ai.goalWeight": "Goal weight",
        "ai.goalWeightNone": "No goal set — the calorie range follows your training goal.",
        "ai.goalWeightHold": "Maintain weight.",
        "ai.goalWeightLose": "Lose {kg} kg — the plan uses a deficit.",
        "ai.goalWeightGain": "Gain {kg} kg — the plan uses a surplus.",
        "ai.goalWeightClear": "Clear goal",
        "settings.title": "Settings",
        "settings.account": "Account",
        "settings.language": "Language",
        "settings.pro": "Pro",
        "settings.proActive": "Pro is active",
        "settings.proInactive": "Pro is not active",
        "settings.proHint": "The AI coach, saving and favourites are part of Pro.",
        "settings.restorePurchases": "Restore purchases",
        "settings.legal": "Legal",
        "legal.imprint": "Imprint",
        "legal.privacy": "Privacy",
        "legal.placeholderWarning": "This text is still a scaffold. The entries in angle brackets must be replaced with the operator's real details before release (LegalView.swift).",
        "auth.title": "Account",
        "auth.signIn": "Sign in",
        "auth.signUp": "Sign up",
        "auth.signOut": "Sign out",

        "auth.deleteAccount": "Delete account",
        "auth.deleteAccountHint": "Permanently deletes your account and all data",
        "auth.deleteConfirmTitle": "Delete account for good?",
        "auth.deleteConfirmBody": "Your account, every saved plan, favourite, meal guide and your body data will be deleted. This cannot be undone.",
        "auth.deleteConfirmAction": "Delete",
        "auth.deleteCancel": "Cancel",
        "auth.deleteDoneTitle": "Account deleted",
        "auth.deleteDoneBody": "Your account and all its data are gone. You can keep rolling workouts without an account.",
        "auth.deleteFailedTitle": "Deletion failed",
        "auth.deleteFailedBody": "Nothing was deleted — your account is still there. Reason: {reason}. Try again later or email us at appoint.20@gmail.com.",
        "auth.deleteNoSession": "No active session — please sign in again.",
        "auth.deleteNotSupported": "The server does not accept deletion requests yet",
        "auth.signInOrUp": "Sign in or sign up",
        "auth.signedIn": "Signed in",
        "auth.email": "Email",
        "auth.password": "Password",
        "auth.whyAccount": "With an account the AI coach generates plans on the server instead of on your device.",
        "auth.hintSignIn": "The app works without an account — the AI coach then computes locally.",
        "auth.hintSignUp": "At least six characters. Depending on the service settings you may need to confirm your email address afterwards.",
        "auth.confirmEmail": "Almost done: confirm the link in the email, then you can sign in.",
        "auth.invalidInput": "Please enter a valid email address and a password of at least six characters.",
        "auth.notConfigured": "Sign-in isn't set up on the server yet. Please try again later.",
        "auth.invalidCredentials": "That email or password is wrong.",
        "auth.tooManyAttempts": "Too many attempts. Wait a moment and try again.",
        "auth.serverError": "Can't reach the server: {reason}",
        "saved.tabWorkouts": "Workouts",
        "saved.tabAIPlans": "AI Plans",
        "saved.tabMealGuides": "Meal Guides",
        "saved.emptyWorkouts": "No workouts saved yet",
        "saved.emptyAIPlans": "No AI plans saved yet",
        "saved.emptyMealGuides": "No meal guides saved yet",
        "saved.emptyAIPlansHint": "Generate a plan in the AI coach and save it there.",
        "saved.emptyMealGuidesHint": "The meal guide is created together with an AI plan.",
        "saved.saveFailed": "Not saved",
        "saved.open": "Open",
        "saved.close": "Close",
        "exercise.imageHint": "Tap to see the image full screen",
        "saved.days": "{n} days",
        "saved.weeks": "{n} weeks",
        "meal.perDay": "kcal / day",
        "meal.protein": "Protein",
        "meal.carbs": "Carbs",
        "meal.fat": "Fat",
        "meal.timing": "Meal timing",
        "meal.shakes": "Power shakes & supplements",
        "meal.shakeTag": "Shake",
        "meal.save": "Save meal guide",
        "meal.savedTitle": "Saved",
        "meal.savedBody": "The meal guide is now under SAVED → Meal Guides.",
        "meal.failedTitle": "Not saved",
        "meal.failedBody": "The meal guide could not be stored. {reason}",
        "meal.alreadySaved": "Already saved",
        "meal.notes": "Notes",
        "meal.generateFailed": "The Meal Guide could not be generated. Please try again.",
        "meal.regenerate": "Generate Meal Guide",
        "meal.day": "Day",
        "meal.addFood": "+ Add ingredient",
        "meal.addFoodTitle": "Add Food Item / Ingredient",
        "meal.foodName": "Food name",
        "meal.foodAmount": "Amount / Portion (e.g. 100g)",
        "meal.foodCalories": "Calories (kcal)",
        "meal.saveChanges": "Save changes",
        "meal.changesSaved": "Changes saved successfully",
        "meal.shakeTitle": "Protein Shake & Consumption",
        "meal.shakePowder": "Powder amount",
        "meal.shakeLiquid": "Liquid",
        "meal.shakeTiming": "Consumption timing",
        "ai.tabWorkout": "Workout plan",
        "ai.tabNutrition": "Meal Guide",
        "ai.cycleActive": "Active",
        "ai.savePlan": "Save plan",
        "ai.planSavedTitle": "Saved",
        "ai.planSavedBody": "The plan is now under SAVED → AI Plans.",
        "ai.planFailedTitle": "Not saved",
        "ai.planFailedBody": "The plan could not be stored. {reason}",
        "ai.planAlreadySaved": "Already saved",
        "ai.newPlan": "Configure a new plan",
        "ai.badResponse": "unusable response",
        "ai.warmupSection": "Warm-up",
        "live.sourceWatch": "Apple Watch",
        "live.avg": "avg",
        "live.peak": "peak",
        "live.duration": "Duration",
        "live.connectSensor": "Pair heart-rate sensor",
        "live.estimatedNote": "Heart rate and calories are model estimates. Pair a sensor for real measurements.",
        "live.noSensorTitle": "NO SENSOR CONNECTED",
        "live.noSensorBody": "Connect an Apple Watch or chest strap to the app — then you'll see here how your body is taking today's session.",
        "ai.warmupTitle": "Warm-up",
        "ai.warmup.auto": "Coach decides",
        "ai.warmup.yes": "Yes, always",
        "ai.warmup.no": "No thanks",
        "ai.warmupHint.auto": "based on age and experience",
        "ai.warmupHint.yes": "every day gets a warm-up",
        "ai.warmupHint.no": "straight to the first exercise",
        "ai.warmupLabel": "Warm-up",
        "ai.dietTitle": "Diet",
        "ai.diet.omnivore": "I eat everything",
        "ai.diet.vegetarian": "Vegetarian",
        "ai.diet.lacto_vegetarian": "Lacto-Vegetarian",
        "ai.diet.vegan": "Vegan",
        "ai.workoutTab": "Workout Plan",
        "ai.mealGuideTab": "Meal Guide",
        "ai.nutritionTitle": "Nutrition Plan & Meal Guide",
        "ai.perDay": "day",
        "ai.protein": "Protein",
        "ai.carbs": "Carbs",
        "ai.fat": "Fat",
        "ai.shakes": "Protein shakes",
        "ai.nutritionDisclaimer": "Guide values based on what you entered, not dietary advice. With existing conditions, medication, or during pregnancy and breastfeeding, check with a doctor first.",
        "live.set": "Set",
        "live.restOverBody": "Rest is over — back to it!",
        "music.title": "Gym music",
        "music.close": "Close",
        "music.offline": "Offline Library",
        "music.streaming": "Streaming",
        "music.add": "Import tracks from Apple Music / Device",
        "music.importing": "Importing tracks…",
        "music.remove": "Remove from playlist",
        "music.prev": "Previous track",
        "music.next": "Next track",
        "music.playPause": "Play / pause",
        "music.emptyTitle": "No music stored yet",
        "music.emptyText": "Add MP3 or M4A files from your device. They stay saved and play at the gym even with no signal.",
        "music.usage": "{n} tracks · {size} on this device",
        "music.noStorage": "This browser cannot store music offline.",
        "music.lockScreenHint": "Keeps playing with the screen off — the track and your current exercise show on the lock screen and on Apple Watch.",
        "music.consentTitle": "Streaming loads external content",
        "music.consentText": "Spotify and YouTube set their own cookies and see your IP address as soon as the player loads. Offline music works without that.",
        "music.consentAccept": "Got it, load streaming",
        "music.closeStream": "Close player",
        "music.needsInternet": "needs internet",

        "music.spotifyTitle": "Spotify",
        "music.spotifyHint": "Opens Spotify — pick your playlist there and it keeps playing while you train.",
        "music.spotifyOpen": "Open Spotify",
        "music.spotifyBrowseWorkout": "Browse workout playlists",
        "music.spotifyNotInstalled": "Spotify isn't installed — the button opens your browser instead.",
        "common.loading": "Loading…",
        "common.cancel": "Cancel",
        "common.search": "Search exercise…",
        "live.title": "LIVE WORKOUT",
        "live.exerciseOf": "Exercise {current} of {total}",
        "live.setOf": "Set {current} of {total}",
        "live.repsTarget": "{reps} reps",
        "live.rest": "REST",
        "live.paused": "PAUSED",
        "live.pauseSession": "Pause workout",
        "live.resumeSession": "Resume workout",
        "live.weight": "WEIGHT",
        "live.reps": "REPS",
        "live.last": "LAST",
        "live.target": "TARGET",
        "live.completeSet": "COMPLETE SET",
        "live.saveSet": "SAVE SET {n}",
        "live.addRest": "+30 s Rest",
        "live.skipRest": "End Rest",
        "live.skipExercise": "Skip Exercise",
        "live.nextExercise": "Next Exercise",
        "live.upNext": "UP NEXT",
        "live.deferred": "LATER",
        "live.modeFocus": "Focus",
        "live.modeLog": "Set Log",
        "live.endSession": "End Workout",
        "live.confirmEnd": "Are you sure you want to end this workout?",
        "live.finished": "🎉 WORKOUT COMPLETE!",
        "live.finishedSub": "Great job! Your session is in the books.",
        "live.totalTime": "TOTAL TIME",
        "live.totalSets": "SETS COMPLETED",
        "live.totalExercises": "EXERCISES",
        "live.close": "Done & Close",
        "live.startTraining": "START WORKOUT",
        "live.calories": "kcal",
        "live.caloriesBurned": "Calories",
        "live.heartRate": "Heart Rate",
        "live.avgHeartRate": "AVERAGE HR",
        "live.peakHeartRate": "PEAK HR",
        "live.volume": "Volume",
        "live.totalVolume": "TOTAL VOLUME",
        "live.connectWatch": "Connect Watch / Sensor",
        "live.connected": "Connected",
        "live.notConnected": "Live Estimate",
        "live.appleHealthSync": "Apple Health active",
        "live.exportHealth": "Save to Apple Health",
        "live.zone1": "Recovery",
        "live.zone2": "Fat Burn",
        "live.zone3": "Aerobic",
        "live.zone4": "Anaerobic",
        "live.zone5": "Peak",
        "ai.biometricsTitle": "Body & Biometrics",
        "ai.sex": "Sex",
        "ai.sexMale": "Male",
        "ai.sexFemale": "Female",
        "ai.sexOther": "Other",
        "ai.age": "Age",
        "ai.height": "Height (cm)",
        "ai.weight": "Weight (kg)",
        "ai.years": "years",
        "ai.step": "Step {current} of {total}",
        "ai.next": "NEXT",
        "ai.back": "Back",
        "ai.review": "Review & Start",
        "ai.reviewSummary": "Profile Overview",
        "ai.quickLimitations": "Common Limitations",
        "ai.limitNone": "No limitations",
        "ai.limitKnee": "Protect knees",
        "ai.limitShoulder": "Protect shoulders",
        "ai.limitOverhead": "No overhead pressing",
        "ai.limitBack": "Protect lower back",
        "ai.limitWrists": "Protect wrists",
        "live.lockScreenCard": "Live Activity / Lock Screen",
        "live.watchMode": "Apple Watch Controller",
        "live.wakeLockActive": "Focus active · Screen stays awake",
        "crash.title": "SOMETHING WENT WRONG",
        "crash.text": "The app hit an unexpected error. Reloading usually helps — saved plans are safe.",
        "crash.reload": "RELOAD",
        "local.title": "Local mode:",
        "local.text": "Without a connection to the service, plans stay on this device only and the AI coach is unreachable.",

        "ai.somatotypeTitle": "BODY TYPE",
        "ai.activityTitle": "DAILY LIFE & LIFESTYLE",
        "ai.pushups": "Push-ups in a row",
        "ai.pullups": "Pull-ups in a row",
        "ai.plank": "Plank hold",

        "ai.equipmentAllHint": "Full gym equipment",
        "challenge.wantTitle": "HOME CHALLENGE",
        "challenge.wantText": "A multi-day challenge for home, no gym needed. Want one? If not we'll skip these questions — you can set it up later in Settings.",
        "challenge.wantYes": "Yes, set it up",
        "challenge.wantNo": "No thanks",
        "challenge.disabledTitle": "Home challenge is off",
        "challenge.disabledText": "You turned the challenge down in the questionnaire. Switch it on in your profile to start one.",

        "dayEdit.title": "EDIT DAY",
        "dayEdit.edit": "Edit",
        "dayEdit.reroll": "Reroll",
        "dayEdit.replace": "Swap",
        "dayEdit.remove": "Remove",
        "dayEdit.add": "Add exercise",
        "dayEdit.shuffleDay": "Shuffle day",

        "planSetup.title": "PLAN SETUP",
        "planSetup.subtitle": "Split, method, volume & cycles",
        "planSetup.cycles": "CYCLES",
        "planSetup.activeNote": "The running plan keeps its exercises. This selection applies to your next plan — change individual days directly on the day via \"Edit\".",

        "saved.setActive": "Start as plan",
        "saved.setActiveTitle": "START AS TRAINING PLAN",
        "saved.setActiveBody": "\"{name}\" becomes your running training plan. You'll track it in the Training Plan tab with weeks and cycles.",
        "saved.setActiveReplace": "\"{name}\" replaces your running training plan. Your current progress will be lost.",

        "ai.gateTitle": "{done} of {total} videos watched",
        "ai.gateText": "The AI coach is a Pro feature. For free you unlock one plan at a time with short videos — that applies to every further plan too.",
        "ai.gateWatch": "WATCH VIDEO",
        "ai.gateSkipWithPro": "Skip the videos with Pro — any time",

        // Sign-in wall at launch
        "gate.title": "WELCOME",
        "gate.subtitle": "Sign in to keep your plans, your progress and the AI coach across all your devices.",
        "gate.signUp": "CREATE ACCOUNT",
        "gate.signIn": "SIGN IN",
        "gate.why": "Why an account?",
        "gate.whyText": "Your training plans, your progress and your Pro subscription belong to the account — not to the device.",

        // Questionnaire after registration
        "onboarding.welcomeTitle": "PLANS THAT FIT YOU",
        "onboarding.welcomeText": "Tell us about your body, your goal and your equipment, and the coach builds plans that actually fit you. It takes two minutes — or you can do it later.",
        "onboarding.setupProfile": "SET UP MY PROFILE",
        "onboarding.jumpIn": "JUMP RIGHT IN",
        "onboarding.laterHint": "You can fill in your profile any time from Settings.",
        "onboarding.start": "GET STARTED",
        "onboarding.later": "Fill in later",
        "onboarding.step": "Step {current} of {total}",
        "onboarding.next": "NEXT",
        "onboarding.back": "Back",
        "onboarding.finish": "DONE",
        "onboarding.titleBody": "Your body",
        "onboarding.titleGoal": "Your goal",
        "onboarding.titleTraining": "Your training",
        "onboarding.titleChallenge": "Your home challenge",
        "onboarding.titleNutrition": "Nutrition & limitations",
        "onboarding.titleHealth": "Apple Health",
        "onboarding.doneTitle": "ALL SET",
        "onboarding.doneText": "Your profile is ready. You can change any value in Settings at any time.",

        // Apple Health
        "health.title": "Connect Apple Health",
        "health.text": "Kraftwürfel takes your weight, height and body data from Health so you don't have to type them — and writes finished workouts back.",
        "health.readTitle": "Read",
        "health.readItems": "Heart rate, weight, height, body fat, date of birth",
        "health.writeTitle": "Written",
        "health.writeItems": "Weight, body fat, finished workouts",
        "health.estimateNote": "Estimated values are never written to Health — only measurements and what you entered yourself.",
        "health.connect": "CONNECT",
        "health.skip": "Continue without Health",
        "health.connected": "Connected",
        "health.unavailable": "Not available on this device",
        "health.prefilled": "{count} values taken from Health",
        "health.nothingRead": "Nothing taken over — you can enter the values yourself next.",

        // Profile in Settings
        "settings.profile": "Your profile",
        "profile.title": "YOUR PROFILE",
        "profile.subtitle": "The AI coach and the home challenge use these answers. Changes apply to your next plan.",
        "profile.sectionBody": "BODY",
        "profile.sectionGoal": "GOAL & EXPERIENCE",
        "profile.sectionTraining": "TRAINING",
        "profile.sectionChallenge": "HOME CHALLENGE",
        "profile.sectionNutrition": "NUTRITION",
        "profile.sectionHealth": "APPLE HEALTH",
        "profile.incompleteTitle": "Profile not filled in yet",
        "profile.incompleteText": "Answer the questionnaire once and the coach will build your plan without asking again.",
        "profile.incompleteCta": "FILL IN QUESTIONNAIRE",
        "profile.shakesTitle": "Protein shakes",
        "profile.shakesLabel": "I drink shakes",
        "profile.shakesHint": "Only used for this: we remind you 30 minutes after training. Off if you don't drink them.",
        "profile.limitations": "Notes & limitations for the coach (optional)",
        "profile.limitationsHint": "e.g. \"sensitive knees, no jumping, keep rests short\"",
        "profile.selfAssessment": "SELF-ASSESSMENT",

        // One-tap generation
        "ready.profileTitle": "YOUR PROFILE",
        "ready.edit": "Edit",
        "ready.generateCoach": "CREATE PLAN",
        "ready.generateChallenge": "START CHALLENGE",
        "ready.coachText": "The coach builds your plan from the answers in your profile.",
        "ready.challengeText": "Your challenge is built from the answers in your profile.",
    ]
}
